# Generated by Django 6.0.1 on 2026-02-12 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
