# Generated by Django 6.0.1 on 2026-02-12 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_telegram_chat_id_profile_telegram_token'),
    ]

    def forwards_func(apps, schema_editor):
        Profile = apps.get_model("accounts", "Profile")
        import uuid

        for profile in Profile.objects.all():
            profile.telegram_token = uuid.uuid4()
            profile.save()

    operations = [
        migrations.RunPython(forwards_func),
    ]