# Generated by Django 6.0.1 on 2026-01-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stox', '0002_form_created_at_form_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Price',
        ),
    ]
