# Generated by Django 6.0.1 on 2026-01-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stox', '0003_rename_form_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockXPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10000)),
                ('size', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
