# Generated by Django 6.0.1 on 2026-02-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stox', '0005_stockxprice_url_stockxprice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockxprice',
            name='region',
            field=models.CharField(default='en-US', max_length=10),
        ),
    ]
