# Generated by Django 6.0.1 on 2026-02-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stox', '0006_stockxprice_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockxprice',
            name='region',
        ),
    ]
